info:
  contact:
    name: dhw
  description: 一个简洁的商品抢购网站
  title: 微商品抢购
  version: "1.0"
paths:
  /api/v1/getgood/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 查看的商品ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 查看商品
  /api/v1/getuser/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 查询的用户ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 查看用户信息
  /api/v1/getusers:
    get:
      consumes:
      - application/json
      parameters:
      - description: 页面大小
        in: query
        name: pageSize
        type: string
      - description: 页面数
        in: query
        name: pageNum
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取用户组
  /api/v1/goods/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: 编辑更改的商品ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 编辑更改商品
  /api/v1/goods/add:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 添加商品
  /api/v1/login:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 登录
  /api/v1/preseckill/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: 预先抢购商品ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 预先抢购商品
  /api/v1/seckill/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: 抢购商品ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 抢购商品
  /api/v1/users/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: 用户ID
        in: query
        name: id
        type: string
      produces:
      - application/json
      responses: {}
      summary: 更新用户
  /api/v1/users/add:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses: {}
      summary: 添加用户
swagger: "2.0"
